import {
  LayoutDashboard, Users, UserCog, Truck, Car, Package, Tag, Receipt, Bell,
  MessageSquare, Map, Image as ImageIcon, Layers, HelpCircle, Building2,
  Star, Settings, ShieldCheck, LogOut, Search, BellRing, Printer, Calendar,
  ChevronDown, ChevronRight, Menu, X, Filter, MoreHorizontal, Eye, Pencil,
  Trash2, Plus, ArrowRight, ArrowUp, ArrowDown, CheckCircle2, Clock,
  CircleDot, MapPin, Bike, UserPlus, IndianRupee, TrendingUp, FileText,
  Send, Download, Phone, Mail, Wallet, Tags, Sparkles, ChartBar, ChartLine,
  Boxes, BadgePercent, Wrench, Palette, PanelLeft, PanelLeftClose, ChevronLeft, type LucideIcon,
} from "lucide-react";

export const Icons = {
  dashboard: LayoutDashboard,
  users: Users,
  subAdmins: UserCog,
  drivers: Truck,
  vehicles: Car,
  goods: Boxes,
  packages: Package,
  coupons: Tag,
  transactions: Receipt,
  notifications: Bell,
  support: MessageSquare,
  cities: Map,
  banners: ImageIcon,
  sections: Layers,
  faq: HelpCircle,
  company: Building2,
  reviews: Star,
  settings: Settings,
  fleet: ShieldCheck,
  vehicleCats: Tags,
  logout: LogOut,
  search: Search,
  bell: BellRing,
  printer: Printer,
  calendar: Calendar,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  menu: Menu,
  close: X,
  filter: Filter,
  more: MoreHorizontal,
  view: Eye,
  edit: Pencil,
  delete: Trash2,
  plus: Plus,
  arrowRight: ArrowRight,
  up: ArrowUp,
  down: ArrowDown,
  check: CheckCircle2,
  clock: Clock,
  dot: CircleDot,
  pin: MapPin,
  bike: Bike,
  userPlus: UserPlus,
  rupee: IndianRupee,
  trending: TrendingUp,
  file: FileText,
  send: Send,
  download: Download,
  phone: Phone,
  mail: Mail,
  wallet: Wallet,
  package: Package,
  car: Car,
  truck: Truck,
  star: Star,
  mapPin: MapPin,
  sparkles: Sparkles,
  chartBar: ChartBar,
  chartLine: ChartLine,
  receipt: Receipt,
  badge: BadgePercent,
  wrench: Wrench,
  palette: Palette,
  panelLeft: PanelLeft,
  panelLeftClose: PanelLeftClose,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof Icons;
