/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as VehicleCategoriesRouteImport } from './routes/vehicle-categories'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SupportChatRouteImport } from './routes/support-chat'
import { Route as SubAdminsRouteImport } from './routes/sub-admins'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HomeSectionsRouteImport } from './routes/home-sections'
import { Route as HomeBannersRouteImport } from './routes/home-banners'
import { Route as GoodsTypesRouteImport } from './routes/goods-types'
import { Route as FleetOwnersRouteImport } from './routes/fleet-owners'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as IndexRouteImport } from './routes/index'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleCategoriesRoute = VehicleCategoriesRouteImport.update({
  id: '/vehicle-categories',
  path: '/vehicle-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportChatRoute = SupportChatRouteImport.update({
  id: '/support-chat',
  path: '/support-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SubAdminsRoute = SubAdminsRouteImport.update({
  id: '/sub-admins',
  path: '/sub-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSectionsRoute = HomeSectionsRouteImport.update({
  id: '/home-sections',
  path: '/home-sections',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeBannersRoute = HomeBannersRouteImport.update({
  id: '/home-banners',
  path: '/home-banners',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodsTypesRoute = GoodsTypesRouteImport.update({
  id: '/goods-types',
  path: '/goods-types',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetOwnersRoute = FleetOwnersRouteImport.update({
  id: '/fleet-owners',
  path: '/fleet-owners',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cities': typeof CitiesRoute
  '/company': typeof CompanyRoute
  '/coupons': typeof CouponsRoute
  '/drivers': typeof DriversRoute
  '/faqs': typeof FaqsRoute
  '/fleet-owners': typeof FleetOwnersRoute
  '/goods-types': typeof GoodsTypesRoute
  '/home-banners': typeof HomeBannersRoute
  '/home-sections': typeof HomeSectionsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/packages': typeof PackagesRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/sub-admins': typeof SubAdminsRoute
  '/support-chat': typeof SupportChatRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/vehicle-categories': typeof VehicleCategoriesRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cities': typeof CitiesRoute
  '/company': typeof CompanyRoute
  '/coupons': typeof CouponsRoute
  '/drivers': typeof DriversRoute
  '/faqs': typeof FaqsRoute
  '/fleet-owners': typeof FleetOwnersRoute
  '/goods-types': typeof GoodsTypesRoute
  '/home-banners': typeof HomeBannersRoute
  '/home-sections': typeof HomeSectionsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/packages': typeof PackagesRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/sub-admins': typeof SubAdminsRoute
  '/support-chat': typeof SupportChatRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/vehicle-categories': typeof VehicleCategoriesRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cities': typeof CitiesRoute
  '/company': typeof CompanyRoute
  '/coupons': typeof CouponsRoute
  '/drivers': typeof DriversRoute
  '/faqs': typeof FaqsRoute
  '/fleet-owners': typeof FleetOwnersRoute
  '/goods-types': typeof GoodsTypesRoute
  '/home-banners': typeof HomeBannersRoute
  '/home-sections': typeof HomeSectionsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/packages': typeof PackagesRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/sub-admins': typeof SubAdminsRoute
  '/support-chat': typeof SupportChatRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/vehicle-categories': typeof VehicleCategoriesRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cities'
    | '/company'
    | '/coupons'
    | '/drivers'
    | '/faqs'
    | '/fleet-owners'
    | '/goods-types'
    | '/home-banners'
    | '/home-sections'
    | '/notifications'
    | '/orders'
    | '/packages'
    | '/reviews'
    | '/settings'
    | '/sub-admins'
    | '/support-chat'
    | '/transactions'
    | '/users'
    | '/vehicle-categories'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cities'
    | '/company'
    | '/coupons'
    | '/drivers'
    | '/faqs'
    | '/fleet-owners'
    | '/goods-types'
    | '/home-banners'
    | '/home-sections'
    | '/notifications'
    | '/orders'
    | '/packages'
    | '/reviews'
    | '/settings'
    | '/sub-admins'
    | '/support-chat'
    | '/transactions'
    | '/users'
    | '/vehicle-categories'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/cities'
    | '/company'
    | '/coupons'
    | '/drivers'
    | '/faqs'
    | '/fleet-owners'
    | '/goods-types'
    | '/home-banners'
    | '/home-sections'
    | '/notifications'
    | '/orders'
    | '/packages'
    | '/reviews'
    | '/settings'
    | '/sub-admins'
    | '/support-chat'
    | '/transactions'
    | '/users'
    | '/vehicle-categories'
    | '/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitiesRoute: typeof CitiesRoute
  CompanyRoute: typeof CompanyRoute
  CouponsRoute: typeof CouponsRoute
  DriversRoute: typeof DriversRoute
  FaqsRoute: typeof FaqsRoute
  FleetOwnersRoute: typeof FleetOwnersRoute
  GoodsTypesRoute: typeof GoodsTypesRoute
  HomeBannersRoute: typeof HomeBannersRoute
  HomeSectionsRoute: typeof HomeSectionsRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  PackagesRoute: typeof PackagesRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
  SubAdminsRoute: typeof SubAdminsRoute
  SupportChatRoute: typeof SupportChatRoute
  TransactionsRoute: typeof TransactionsRoute
  UsersRoute: typeof UsersRoute
  VehicleCategoriesRoute: typeof VehicleCategoriesRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-categories': {
      id: '/vehicle-categories'
      path: '/vehicle-categories'
      fullPath: '/vehicle-categories'
      preLoaderRoute: typeof VehicleCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-chat': {
      id: '/support-chat'
      path: '/support-chat'
      fullPath: '/support-chat'
      preLoaderRoute: typeof SupportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-admins': {
      id: '/sub-admins'
      path: '/sub-admins'
      fullPath: '/sub-admins'
      preLoaderRoute: typeof SubAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-sections': {
      id: '/home-sections'
      path: '/home-sections'
      fullPath: '/home-sections'
      preLoaderRoute: typeof HomeSectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-banners': {
      id: '/home-banners'
      path: '/home-banners'
      fullPath: '/home-banners'
      preLoaderRoute: typeof HomeBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goods-types': {
      id: '/goods-types'
      path: '/goods-types'
      fullPath: '/goods-types'
      preLoaderRoute: typeof GoodsTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-owners': {
      id: '/fleet-owners'
      path: '/fleet-owners'
      fullPath: '/fleet-owners'
      preLoaderRoute: typeof FleetOwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitiesRoute: CitiesRoute,
  CompanyRoute: CompanyRoute,
  CouponsRoute: CouponsRoute,
  DriversRoute: DriversRoute,
  FaqsRoute: FaqsRoute,
  FleetOwnersRoute: FleetOwnersRoute,
  GoodsTypesRoute: GoodsTypesRoute,
  HomeBannersRoute: HomeBannersRoute,
  HomeSectionsRoute: HomeSectionsRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  PackagesRoute: PackagesRoute,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
  SubAdminsRoute: SubAdminsRoute,
  SupportChatRoute: SupportChatRoute,
  TransactionsRoute: TransactionsRoute,
  UsersRoute: UsersRoute,
  VehicleCategoriesRoute: VehicleCategoriesRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
